/**
 * Hand-authored OpenAPI 3.0 description of the endpoints this codebase owns
 * (auth.controller / users.controller / handle.controller / index router).
 * Better Auth's own endpoints under /api/auth/* are documented separately
 * (see the `Better Auth` tag) since they're generated by the library, not us —
 * see readme-files/BACKEND_STRUCTURE.md §5d for the authoritative list.
 */

const apiResponseSchema = {
  type: "object",
  properties: {
    status: { type: "string", enum: ["success", "error"] },
    statusCode: { type: "integer" },
    message: { type: "string" },
    data: {},
  },
  required: ["status", "statusCode", "message"],
};

const validationErrorResponseSchema = {
  allOf: [
    { $ref: "#/components/schemas/ApiResponse" },
    {
      type: "object",
      properties: {
        errors: {
          type: "object",
          additionalProperties: { type: "array", items: { type: "string" } },
        },
      },
    },
  ],
};

const publicUserSchema = {
  type: "object",
  properties: {
    id: { type: "string" },
    name: { type: "string" },
    email: { type: "string", format: "email" },
    image: { type: "string", nullable: true },
    imageSource: { type: "string", enum: ["oauth", "user"], nullable: true },
    emailVerified: { type: "boolean" },
  },
  required: ["id", "name", "email", "emailVerified"],
};

const sessionUserSchema = {
  type: "object",
  properties: {
    id: { type: "string" },
    email: { type: "string", format: "email" },
    name: { type: "string" },
    emailVerified: { type: "boolean" },
    handle: { type: "string", nullable: true },
  },
  required: ["id", "email", "name", "emailVerified", "handle"],
};

const handleMetadataSchema = {
  type: "object",
  properties: {
    handle: { type: "string", nullable: true },
    changesRemaining: { type: "integer" },
    isChangeLocked: { type: "boolean" },
    cooldownResetAt: { type: "string", format: "date-time", nullable: true },
    revertableHandle: { type: "string", nullable: true },
    revertableExpiresAt: { type: "string", format: "date-time", nullable: true },
  },
};

const handleAvailabilitySchema = {
  type: "object",
  properties: {
    status: { type: "string", enum: ["available", "taken", "revertable", "current", "invalid"] },
    handle: { type: "string" },
    reason: { type: "string" },
    suggestions: { type: "array", items: { type: "string" } },
  },
  required: ["status", "handle"],
};

const linkedAccountSchema = {
  type: "object",
  properties: {
    providerId: { type: "string", enum: ["credential", "google", "github"] },
    linkedEmail: { type: "string", format: "email" },
  },
  required: ["providerId", "linkedEmail"],
};

function envelope(dataSchema: Record<string, unknown>): Record<string, unknown> {
  return {
    allOf: [
      { $ref: "#/components/schemas/ApiResponse" },
      { type: "object", properties: { data: dataSchema } },
    ],
  };
}

const cookieAuthNote =
  "Session cookie set by Better Auth (httpOnly, signed). Sent automatically by the " +
  'browser on same-origin fetches made with `credentials: "include"`.';

export const openApiSpec = {
  openapi: "3.0.3",
  info: {
    title: "Qatoto API",
    version: "0.1.0",
    description:
      "Auth + identity surface for the Qatoto backend. See readme-files/BACKEND_STRUCTURE.md " +
      "for the full narrative contract this spec summarizes.",
  },
  servers: [{ url: "/", description: "Current origin" }],
  tags: [
    { name: "System", description: "Health checks" },
    { name: "Signup", description: "OTP-gated signup, owned by this codebase (not Better Auth)" },
    { name: "Session", description: "Current-user lookup" },
    { name: "Users", description: "Profile, photo, linked-account endpoints" },
    { name: "Handles", description: "Username claim/availability endpoints" },
    {
      name: "Better Auth",
      description:
        "Generated by the Better Auth library at /api/auth/* — login, OAuth, passkeys, " +
        "OTP send, sign-out, get-session. Not authored here; see BACKEND_STRUCTURE.md §5d.",
    },
  ],
  components: {
    securitySchemes: {
      sessionCookie: {
        type: "apiKey",
        in: "cookie",
        name: "better-auth.session_token",
        description: cookieAuthNote,
      },
    },
    schemas: {
      ApiResponse: apiResponseSchema,
      ValidationErrorResponse: validationErrorResponseSchema,
      PublicUser: publicUserSchema,
      SessionUser: sessionUserSchema,
      HandleMetadata: handleMetadataSchema,
      HandleAvailability: handleAvailabilitySchema,
      LinkedAccount: linkedAccountSchema,
    },
    responses: {
      ValidationFailed: {
        description: "422 — request body/query failed Zod `.safeParse()`.",
        content: {
          "application/json": { schema: { $ref: "#/components/schemas/ValidationErrorResponse" } },
        },
      },
      Unauthorized: {
        description: "401 — no valid session cookie.",
        content: {
          "application/json": { schema: { $ref: "#/components/schemas/ApiResponse" } },
        },
      },
      NotFound: {
        description: "404 — resource does not exist.",
        content: {
          "application/json": { schema: { $ref: "#/components/schemas/ApiResponse" } },
        },
      },
    },
  },
  paths: {
    "/": {
      get: {
        tags: ["System"],
        summary: "Welcome / liveness",
        responses: {
          "200": { description: "OK", content: { "application/json": { schema: envelope({}) } } },
        },
      },
    },
    "/health": {
      get: {
        tags: ["System"],
        summary: "Health check for load balancers",
        responses: { "200": { description: "OK" } },
      },
    },
    "/signup/start": {
      post: {
        tags: ["Signup"],
        summary: "Phase 1 of signup — send a verification OTP",
        description:
          "Creates no user. Always returns a generic 200 so the endpoint can't be used to " +
          "probe which emails are registered. Rate limited per-IP and per-email.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: { email: { type: "string", format: "email" } },
                required: ["email"],
                additionalProperties: false,
              },
            },
          },
        },
        responses: {
          "200": {
            description:
              "OTP dispatched (or silently no-op'd) regardless of whether the email exists.",
            content: { "application/json": { schema: envelope({ type: "object" }) } },
          },
          "422": { $ref: "#/components/responses/ValidationFailed" },
          "429": { description: "Too many requests for this IP or email." },
        },
      },
    },
    "/signup/complete": {
      post: {
        tags: ["Signup"],
        summary: "Phase 2 of signup — verify OTP + set password, atomically",
        description:
          "The only place an account is created. Resolves to exactly one user via three " +
          "paths: brand-new signup, OAuth-only user gaining a password (linked, not " +
          "duplicated), or a genuine re-signup (rejected). See BACKEND_STRUCTURE.md §5e.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  email: { type: "string", format: "email" },
                  otp: { type: "string" },
                  password: { type: "string", minLength: 8 },
                  name: { type: "string" },
                },
                required: ["email", "otp", "password"],
                additionalProperties: false,
              },
            },
          },
        },
        responses: {
          "201": {
            description:
              "Account created or password linked onto the existing user. Sets the session cookie.",
            content: { "application/json": { schema: envelope({ type: "object" }) } },
          },
          "401": { description: "Invalid or expired OTP. Nothing was created." },
          "409": { description: "Email already has a password — sign in instead." },
          "422": { $ref: "#/components/responses/ValidationFailed" },
        },
      },
    },
    "/me": {
      get: {
        tags: ["Session"],
        summary: "The currently authenticated user",
        security: [{ sessionCookie: [] }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({ $ref: "#/components/schemas/SessionUser" }),
              },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
        },
      },
    },
    "/users": {
      get: {
        tags: ["Users"],
        summary: "List users",
        description: "Currently public — see BACKEND_STRUCTURE.md §9 'Later' list.",
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({
                  type: "array",
                  items: { $ref: "#/components/schemas/PublicUser" },
                }),
              },
            },
          },
        },
      },
    },
    "/users/{id}": {
      get: {
        tags: ["Users"],
        summary: "Get a user by id",
        description: "Currently public — see BACKEND_STRUCTURE.md §9 'Later' list.",
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": { schema: envelope({ $ref: "#/components/schemas/PublicUser" }) },
            },
          },
          "404": { $ref: "#/components/responses/NotFound" },
        },
      },
    },
    "/users/me": {
      patch: {
        tags: ["Users"],
        summary: "Set the caller's display name",
        description:
          "The user id comes from the session, never the body — a caller can only rename themselves.",
        security: [{ sessionCookie: [] }],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: { fullName: { type: "string", minLength: 1, maxLength: 100 } },
                required: ["fullName"],
                additionalProperties: false,
              },
            },
          },
        },
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": { schema: envelope({ $ref: "#/components/schemas/PublicUser" }) },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "422": { $ref: "#/components/responses/ValidationFailed" },
        },
      },
    },
    "/users/me/photo": {
      patch: {
        tags: ["Users"],
        summary: "Set the caller's profile photo",
        description:
          "multipart/form-data, field `photo`, 5MB cap. sharp decodes/validates/normalizes " +
          "the bytes server-side before Cloudinary upload.",
        security: [{ sessionCookie: [] }],
        requestBody: {
          required: true,
          content: {
            "multipart/form-data": {
              schema: {
                type: "object",
                properties: { photo: { type: "string", format: "binary" } },
                required: ["photo"],
              },
            },
          },
        },
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": { schema: envelope({ $ref: "#/components/schemas/PublicUser" }) },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "413": { description: "File exceeds the 5 MB cap." },
          "422": {
            description: "Not a decodable image, unsupported format, or out-of-bounds dimensions.",
          },
          "502": { description: "Cloudinary upload failed." },
          "503": { description: "Cloudinary is not configured." },
        },
      },
      delete: {
        tags: ["Users"],
        summary: "Remove the caller's profile photo",
        security: [{ sessionCookie: [] }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": { schema: envelope({ $ref: "#/components/schemas/PublicUser" }) },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "502": { description: "Cloudinary delete failed." },
        },
      },
    },
    "/users/me/handle": {
      get: {
        tags: ["Handles"],
        summary: "Handle panel bootstrap",
        description: "Current handle plus rate-limit state and a one-tap revert affordance.",
        security: [{ sessionCookie: [] }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({ $ref: "#/components/schemas/HandleMetadata" }),
              },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
        },
      },
      patch: {
        tags: ["Handles"],
        summary: "Authoritative set/revert of the caller's handle",
        description:
          "Re-normalized, regex-validated, rate-limited (2 changes / 14 days), and " +
          "availability-re-checked inside one atomic transaction.",
        security: [{ sessionCookie: [] }],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: { handle: { type: "string", maxLength: 100 } },
                required: ["handle"],
                additionalProperties: false,
              },
            },
          },
        },
        responses: {
          "200": {
            description: "OK",
            content: { "application/json": { schema: envelope({ type: "object" }) } },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "422": { description: "Handle is invalid or already taken." },
          "429": {
            description: "2-changes-per-14-days cap reached. Body includes `cooldownResetAt`.",
          },
        },
      },
    },
    "/users/me/linked-accounts": {
      get: {
        tags: ["Users"],
        summary: "The caller's linked auth providers",
        description: "Never returns tokens — providerId + the email each provider is linked as.",
        security: [{ sessionCookie: [] }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({
                  type: "array",
                  items: { $ref: "#/components/schemas/LinkedAccount" },
                }),
              },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
        },
      },
    },
    "/handles/availability": {
      get: {
        tags: ["Handles"],
        summary: "Debounced handle availability preview",
        description:
          "Read-only Tier-1 probe, rate-limited 60/min/user. Invalid input is a normal 200 " +
          'preview (status: "invalid"), not a 4xx.',
        security: [{ sessionCookie: [] }],
        parameters: [
          {
            name: "handle",
            in: "query",
            required: true,
            schema: { type: "string", maxLength: 100 },
          },
        ],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({ $ref: "#/components/schemas/HandleAvailability" }),
              },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "422": { $ref: "#/components/responses/ValidationFailed" },
          "429": { description: "More than 60 checks in the last minute." },
        },
      },
    },
    "/api/auth/{splat}": {
      get: {
        tags: ["Better Auth"],
        summary:
          "Better Auth catch-all (GET) — get-session, OAuth redirects, passkey ceremonies, sign-out",
        description:
          "Generated by the `better-auth` library, not this repo. See " +
          "readme-files/BACKEND_STRUCTURE.md §5d for the endpoint table " +
          "(send-verification-otp, sign-in/email, sign-in/social, passkey/*, unlink-account, get-session, ...).",
        parameters: [{ name: "splat", in: "path", required: true, schema: { type: "string" } }],
        responses: { "200": { description: "Varies by sub-route — see Better Auth's own docs." } },
      },
      post: {
        tags: ["Better Auth"],
        summary:
          "Better Auth catch-all (POST) — sign-in, sign-up-blocked OTP, password reset, unlink",
        description:
          "Generated by the `better-auth` library, not this repo. See " +
          "readme-files/BACKEND_STRUCTURE.md §5d for the endpoint table.",
        parameters: [{ name: "splat", in: "path", required: true, schema: { type: "string" } }],
        responses: { "200": { description: "Varies by sub-route — see Better Auth's own docs." } },
      },
    },
  },
};
