import { buildRndPathItems } from "#src/docs/openapi-rnd.js";

/**
 * Hand-authored OpenAPI 3.0 description of the endpoints this codebase owns
 * (auth.controller / users.controller / handle.controller / index router).
 * Better Auth's own endpoints under /api/auth/* are documented separately
 * (see the `Better Auth` tag) since they're generated by the library, not us —
 * see readme-files/BACKEND_STRUCTURE.md §5d for the authoritative list.
 */

const apiResponseSchema = {
  type: "object",
  properties: {
    status: { type: "string", enum: ["success", "error"] },
    statusCode: { type: "integer" },
    message: { type: "string" },
    data: {},
  },
  required: ["status", "statusCode", "message"],
};

/**
 * `errors` is the ONLY validation channel — never `data`, which is the success payload.
 *
 * `form` is a RESERVED key inside it, carrying object-level Zod issues. `.strict()`'s
 * `unrecognized_keys` is the common one, and it is not attributable to any single field, so a
 * client that renders only per-field entries will show nothing for the most common rejection.
 */
const validationErrorResponseSchema = {
  allOf: [
    { $ref: "#/components/schemas/ApiResponse" },
    {
      type: "object",
      properties: {
        errors: {
          type: "object",
          description:
            "Field name to messages. The reserved key `form` carries object-level issues, " +
            "notably the keys rejected by `.strict()`.",
          additionalProperties: { type: "array", items: { type: "string" } },
        },
      },
    },
  ],
};

const publicUserSchema = {
  type: "object",
  properties: {
    id: { type: "string" },
    name: { type: "string" },
    email: { type: "string", format: "email" },
    image: { type: "string", nullable: true },
    imageSource: { type: "string", enum: ["oauth", "user"], nullable: true },
    emailVerified: { type: "boolean" },
  },
  required: ["id", "name", "email", "emailVerified"],
};

const sessionUserSchema = {
  type: "object",
  properties: {
    id: { type: "string" },
    email: { type: "string", format: "email" },
    name: { type: "string" },
    emailVerified: { type: "boolean" },
    handle: { type: "string", nullable: true },
  },
  required: ["id", "email", "name", "emailVerified", "handle"],
};

const handleMetadataSchema = {
  type: "object",
  properties: {
    handle: { type: "string", nullable: true },
    changesRemaining: { type: "integer" },
    isChangeLocked: { type: "boolean" },
    cooldownResetAt: { type: "string", format: "date-time", nullable: true },
    revertableHandle: { type: "string", nullable: true },
    revertableExpiresAt: { type: "string", format: "date-time", nullable: true },
  },
};

const handleAvailabilitySchema = {
  type: "object",
  properties: {
    status: { type: "string", enum: ["available", "taken", "revertable", "current", "invalid"] },
    handle: { type: "string" },
    reason: { type: "string" },
    suggestions: { type: "array", items: { type: "string" } },
  },
  required: ["status", "handle"],
};

const linkedAccountSchema = {
  type: "object",
  properties: {
    providerId: { type: "string", enum: ["credential", "google", "github"] },
    linkedEmail: { type: "string", format: "email" },
  },
  required: ["providerId", "linkedEmail"],
};

function envelope(dataSchema: Record<string, unknown>): Record<string, unknown> {
  return {
    allOf: [
      { $ref: "#/components/schemas/ApiResponse" },
      { type: "object", properties: { data: dataSchema } },
    ],
  };
}

const cookieAuthNote =
  "Session cookie set by Better Auth (httpOnly, signed). Sent automatically by the " +
  'browser on same-origin fetches made with `credentials: "include"`.';

/**
 * ⚠️ THIS FILE COVERS AUTH, USERS, HANDLES AND DISCOVERY IN FULL — and nothing else by
 * hand. The R&D surface is merged in from `openapi-rnd.ts`, which DERIVES its paths from
 * the mounted routers so it cannot drift (§11l.2 item 8).
 *
 * Read the two halves for what they are: the entries below carry request and response
 * schemas; the derived ones carry paths, verbs, parameters and a pointer to the contract.
 */
const handWrittenSpec = {
  openapi: "3.0.3",
  info: {
    title: "Qatoto API",
    version: "0.1.0",
    description:
      "Auth + identity surface for the Qatoto backend. See readme-files/BACKEND_STRUCTURE.md " +
      "for the full narrative contract this spec summarizes.",
  },
  servers: [{ url: "/", description: "Current origin" }],
  tags: [
    { name: "System", description: "Health checks" },
    { name: "Signup", description: "OTP-gated signup, owned by this codebase (not Better Auth)" },
    { name: "Session", description: "Current-user lookup" },
    { name: "Users", description: "Profile, photo, linked-account endpoints" },
    { name: "Handles", description: "Username claim/availability endpoints" },
    {
      name: "Discovery",
      description:
        "Civic Pulse problem map, knowledge hub and talent directory " +
        "(R_AND_D_BACKEND_STRUCTURE.md §6/§11b). Every figure is a raw integer in a " +
        "named unit — the client formats it.",
    },
    {
      name: "Better Auth",
      description:
        "Generated by the Better Auth library at /api/auth/* — login, OAuth, passkeys, " +
        "OTP send, sign-out, get-session. Not authored here; see BACKEND_STRUCTURE.md §5d.",
    },
  ],
  components: {
    securitySchemes: {
      sessionCookie: {
        type: "apiKey",
        in: "cookie",
        name: "better-auth.session_token",
        description: cookieAuthNote,
      },
    },
    schemas: {
      ApiResponse: apiResponseSchema,
      ValidationErrorResponse: validationErrorResponseSchema,
      PublicUser: publicUserSchema,
      SessionUser: sessionUserSchema,
      HandleMetadata: handleMetadataSchema,
      HandleAvailability: handleAvailabilitySchema,
      LinkedAccount: linkedAccountSchema,
    },
    responses: {
      ValidationFailed: {
        description:
          "422 — request body/query failed Zod `.safeParse()`. Detail arrives under `errors`, " +
          "with rejected unknown keys under the reserved `errors.form`.",
        content: {
          "application/json": { schema: { $ref: "#/components/schemas/ValidationErrorResponse" } },
        },
      },
      Unauthorized: {
        description: "401 — no valid session cookie.",
        content: {
          "application/json": { schema: { $ref: "#/components/schemas/ApiResponse" } },
        },
      },
      NotFound: {
        description: "404 — resource does not exist.",
        content: {
          "application/json": { schema: { $ref: "#/components/schemas/ApiResponse" } },
        },
      },
    },
  },
  paths: {
    "/": {
      get: {
        tags: ["System"],
        summary: "Welcome / liveness",
        responses: {
          "200": { description: "OK", content: { "application/json": { schema: envelope({}) } } },
        },
      },
    },
    "/health": {
      get: {
        tags: ["System"],
        summary: "Health check for load balancers",
        responses: { "200": { description: "OK" } },
      },
    },
    "/signup/start": {
      post: {
        tags: ["Signup"],
        summary: "Phase 1 of signup — send a verification OTP",
        description:
          "Creates no user. Always returns a generic 200 so the endpoint can't be used to " +
          "probe which emails are registered. Rate limited per-IP and per-email.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: { email: { type: "string", format: "email" } },
                required: ["email"],
                additionalProperties: false,
              },
            },
          },
        },
        responses: {
          "200": {
            description:
              "OTP dispatched (or silently no-op'd) regardless of whether the email exists.",
            content: { "application/json": { schema: envelope({ type: "object" }) } },
          },
          "422": { $ref: "#/components/responses/ValidationFailed" },
          "429": { description: "Too many requests for this IP or email." },
        },
      },
    },
    "/signup/complete": {
      post: {
        tags: ["Signup"],
        summary: "Phase 2 of signup — verify OTP + set password, atomically",
        description:
          "The only place an account is created. Resolves to exactly one user via three " +
          "paths: brand-new signup, OAuth-only user gaining a password (linked, not " +
          "duplicated), or a genuine re-signup (rejected). See BACKEND_STRUCTURE.md §5e.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  email: { type: "string", format: "email" },
                  otp: { type: "string" },
                  password: { type: "string", minLength: 8 },
                  name: { type: "string" },
                },
                required: ["email", "otp", "password"],
                additionalProperties: false,
              },
            },
          },
        },
        responses: {
          "201": {
            description:
              "Account created or password linked onto the existing user. Sets the session cookie.",
            content: { "application/json": { schema: envelope({ type: "object" }) } },
          },
          "401": { description: "Invalid or expired OTP. Nothing was created." },
          "409": { description: "Email already has a password — sign in instead." },
          "422": { $ref: "#/components/responses/ValidationFailed" },
        },
      },
    },
    "/me": {
      get: {
        tags: ["Session"],
        summary: "The currently authenticated user",
        security: [{ sessionCookie: [] }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({ $ref: "#/components/schemas/SessionUser" }),
              },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
        },
      },
    },
    "/users": {
      get: {
        tags: ["Users"],
        summary: "List users",
        description: "Currently public — see BACKEND_STRUCTURE.md §9 'Later' list.",
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({
                  type: "array",
                  items: { $ref: "#/components/schemas/PublicUser" },
                }),
              },
            },
          },
        },
      },
    },
    "/users/{id}": {
      get: {
        tags: ["Users"],
        summary: "Get a user by id",
        description: "Currently public — see BACKEND_STRUCTURE.md §9 'Later' list.",
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": { schema: envelope({ $ref: "#/components/schemas/PublicUser" }) },
            },
          },
          "404": { $ref: "#/components/responses/NotFound" },
        },
      },
    },
    "/users/me": {
      patch: {
        tags: ["Users"],
        summary: "Set the caller's display name",
        description:
          "The user id comes from the session, never the body — a caller can only rename themselves.",
        security: [{ sessionCookie: [] }],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: { fullName: { type: "string", minLength: 1, maxLength: 100 } },
                required: ["fullName"],
                additionalProperties: false,
              },
            },
          },
        },
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": { schema: envelope({ $ref: "#/components/schemas/PublicUser" }) },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "422": { $ref: "#/components/responses/ValidationFailed" },
        },
      },
    },
    "/users/me/photo": {
      patch: {
        tags: ["Users"],
        summary: "Set the caller's profile photo",
        description:
          "multipart/form-data, field `photo`, 5MB cap. sharp decodes/validates/normalizes " +
          "the bytes server-side before Cloudinary upload.",
        security: [{ sessionCookie: [] }],
        requestBody: {
          required: true,
          content: {
            "multipart/form-data": {
              schema: {
                type: "object",
                properties: { photo: { type: "string", format: "binary" } },
                required: ["photo"],
              },
            },
          },
        },
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": { schema: envelope({ $ref: "#/components/schemas/PublicUser" }) },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "413": { description: "File exceeds the 5 MB cap." },
          "422": {
            description: "Not a decodable image, unsupported format, or out-of-bounds dimensions.",
          },
          "502": { description: "Cloudinary upload failed." },
          "503": { description: "Cloudinary is not configured." },
        },
      },
      delete: {
        tags: ["Users"],
        summary: "Remove the caller's profile photo",
        security: [{ sessionCookie: [] }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": { schema: envelope({ $ref: "#/components/schemas/PublicUser" }) },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "502": { description: "Cloudinary delete failed." },
        },
      },
    },
    "/users/me/handle": {
      get: {
        tags: ["Handles"],
        summary: "Handle panel bootstrap",
        description: "Current handle plus rate-limit state and a one-tap revert affordance.",
        security: [{ sessionCookie: [] }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({ $ref: "#/components/schemas/HandleMetadata" }),
              },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
        },
      },
      patch: {
        tags: ["Handles"],
        summary: "Authoritative set/revert of the caller's handle",
        description:
          "Re-normalized, regex-validated, rate-limited (2 changes / 14 days), and " +
          "availability-re-checked inside one atomic transaction.",
        security: [{ sessionCookie: [] }],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: { handle: { type: "string", maxLength: 100 } },
                required: ["handle"],
                additionalProperties: false,
              },
            },
          },
        },
        responses: {
          "200": {
            description: "OK",
            content: { "application/json": { schema: envelope({ type: "object" }) } },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "422": { description: "Handle is invalid or already taken." },
          "429": {
            description: "2-changes-per-14-days cap reached. Body includes `cooldownResetAt`.",
          },
        },
      },
    },
    "/users/me/linked-accounts": {
      get: {
        tags: ["Users"],
        summary: "The caller's linked auth providers",
        description: "Never returns tokens — providerId + the email each provider is linked as.",
        security: [{ sessionCookie: [] }],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({
                  type: "array",
                  items: { $ref: "#/components/schemas/LinkedAccount" },
                }),
              },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
        },
      },
    },
    "/handles/availability": {
      get: {
        tags: ["Handles"],
        summary: "Debounced handle availability preview",
        description:
          "Read-only Tier-1 probe, rate-limited 60/min/user. Invalid input is a normal 200 " +
          'preview (status: "invalid"), not a 4xx.',
        security: [{ sessionCookie: [] }],
        parameters: [
          {
            name: "handle",
            in: "query",
            required: true,
            schema: { type: "string", maxLength: 100 },
          },
        ],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: envelope({ $ref: "#/components/schemas/HandleAvailability" }),
              },
            },
          },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "422": { $ref: "#/components/responses/ValidationFailed" },
          "429": { description: "More than 60 checks in the last minute." },
        },
      },
    },
    "/discovery/problem-clusters": {
      get: {
        tags: ["Discovery"],
        summary: "List problem clusters for the map",
        description:
          "Public. A CLUSTER is the deduplicated public entity — `distinctReporterCount` " +
          "counts PEOPLE, not submissions. Coordinates are integer microdegrees " +
          "(degrees x 1e6), quantized to a ~111 m grid on publication so a singleton " +
          "cluster does not disclose one reporter's exact address. " +
          "`opportunityScorePoints` is NULL until the nightly job has run — never 0.",
        parameters: [
          {
            name: "category",
            in: "query",
            schema: { type: "string" },
            description: "Category slug",
          },
          { name: "region", in: "query", schema: { type: "string" }, description: "Region slug" },
          {
            name: "minOpportunityScorePoints",
            in: "query",
            schema: { type: "integer", minimum: 0, maximum: 100 },
          },
          { name: "minLatitudeMicrodegrees", in: "query", schema: { type: "integer" } },
          { name: "maxLatitudeMicrodegrees", in: "query", schema: { type: "integer" } },
          { name: "minLongitudeMicrodegrees", in: "query", schema: { type: "integer" } },
          { name: "maxLongitudeMicrodegrees", in: "query", schema: { type: "integer" } },
          {
            name: "sort",
            in: "query",
            schema: { type: "string", enum: ["opportunity", "recent", "reporters"] },
          },
          { name: "page", in: "query", schema: { type: "integer", minimum: 1, maximum: 500 } },
          { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100 } },
        ],
        responses: {
          "200": { description: "A page of clusters." },
          "422": {
            description: "Unknown query key, or a PARTIAL viewport — all four bounds or none.",
          },
        },
      },
    },
    "/discovery/problem-clusters/{clusterId}": {
      get: {
        tags: ["Discovery"],
        summary: "Cluster detail, with linked projects and score history",
        description:
          "A merged or hidden cluster STILL resolves 200 and carries `mergedIntoClusterId`, " +
          "so a shared link follows the merge rather than dying.",
        parameters: [
          {
            name: "clusterId",
            in: "path",
            required: true,
            schema: { type: "string", format: "uuid" },
          },
        ],
        responses: {
          "200": { description: "The cluster." },
          "404": { description: "No such cluster." },
        },
      },
    },
    "/discovery/problem-reports": {
      post: {
        tags: ["Discovery"],
        summary: "Report a problem (202 — clustering is asynchronous)",
        description:
          "Requires an IDENTIFIED account, not merely a session: `distinctReporterCount` is " +
          "the sybil surface of the whole opportunity score, and the anonymous() plugin " +
          "makes a bare session nearly free. " +
          "Takes `locationText`, NOT coordinates — the server forward-geocodes it, because " +
          "§6 forbids client-claimed geography and the country feeds the score. " +
          "`countryCode`, `opportunityScore`, `reportCount`, `status`, `clusterId` and any " +
          "coordinate are rejected with 422 by .strict(). " +
          "Returns a RECEIPT, not a cluster: none of those numbers exists yet.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                additionalProperties: false,
                required: ["title", "categoryId", "description", "locationText"],
                properties: {
                  title: { type: "string", minLength: 8, maxLength: 160 },
                  categoryId: { type: "string", format: "uuid" },
                  description: { type: "string", minLength: 20, maxLength: 5000 },
                  locationText: { type: "string", minLength: 2, maxLength: 200 },
                },
              },
            },
          },
        },
        responses: {
          "202": { description: "Report accepted and queued for geocoding + clustering." },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "403": { description: "Session is anonymous — an identified account is required." },
          "422": { $ref: "#/components/responses/ValidationFailed" },
          "429": { description: "More than 10 reports in 15 minutes." },
        },
      },
    },
    "/discovery/problem-reports/mine": {
      get: {
        tags: ["Discovery"],
        summary: "The caller's own reports, with clustering status",
        description:
          "There is no `userId` parameter and there never will be — the filter is the " +
          "session id (§13). Coordinates are returned UNQUANTIZED here: the reporter " +
          "supplied the location themselves.",
        parameters: [
          {
            name: "clusteringStatus",
            in: "query",
            schema: {
              type: "string",
              enum: ["queued", "clustered", "geocode_failed", "rejected", "failed"],
            },
          },
          { name: "page", in: "query", schema: { type: "integer" } },
          { name: "limit", in: "query", schema: { type: "integer" } },
        ],
        responses: {
          "200": { description: "A page of the caller's reports." },
          "401": { $ref: "#/components/responses/Unauthorized" },
        },
      },
    },
    "/discovery/categories": {
      get: {
        tags: ["Discovery"],
        summary: "List categories (canonical; /research-categories aliases this)",
        description:
          "Defaults to `approved` only — a pending, user-minted category must not appear " +
          "in a public facet or the moderation queue is decorative.",
        parameters: [
          {
            name: "status",
            in: "query",
            schema: { type: "string", enum: ["approved", "pending", "rejected"] },
          },
        ],
        responses: { "200": { description: "Categories." } },
      },
      post: {
        tags: ["Discovery"],
        summary: "Mint a category (lands `pending`)",
        description:
          "`status` and `pinIconKey` are absent by construction — .strict() turns " +
          "self-approval, and choosing your own map icon, into a 422.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                additionalProperties: false,
                required: ["label"],
                properties: { label: { type: "string", minLength: 1, maxLength: 80 } },
              },
            },
          },
        },
        responses: {
          "201": { description: "Submitted for review." },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "409": { description: "A category already resolves to that slug." },
          "422": { $ref: "#/components/responses/ValidationFailed" },
          "429": { description: "More than 5 in 15 minutes." },
        },
      },
    },
    "/discovery/regions": {
      get: {
        tags: ["Discovery"],
        summary: "Region lookup (unpaginated — it sources a select)",
        parameters: [
          {
            name: "countryCode",
            in: "query",
            schema: { type: "string", minLength: 2, maxLength: 2 },
          },
        ],
        responses: { "200": { description: "Regions, ordered by kind then label." } },
      },
    },
    "/discovery/skills": {
      get: {
        tags: ["Discovery"],
        summary: "Canonical skill vocabulary (unpaginated)",
        description:
          "These slugs are what `?skill=` matches BY EQUALITY, which is the structural fix " +
          'for the substring bug where a "Water" chip matched "Water Polo".',
        responses: { "200": { description: "Active skills." } },
      },
    },
    "/discovery/market-insights": {
      get: {
        tags: ["Discovery"],
        summary: "Knowledge-hub insight cards",
        description:
          '`statValue` from the mocks ("+34%", "68M people", "3x coverage") is ' +
          "decomposed into statKind + statValueMilli (value x 1000) + statUnitKey, so the " +
          "client formats both the magnitude and the locale.",
        parameters: [
          { name: "region", in: "query", schema: { type: "string" } },
          { name: "category", in: "query", schema: { type: "string" } },
          {
            name: "statKind",
            in: "query",
            schema: {
              type: "string",
              enum: ["percent_change", "percent_level", "absolute_count", "multiplier"],
            },
          },
          { name: "page", in: "query", schema: { type: "integer" } },
          { name: "limit", in: "query", schema: { type: "integer" } },
        ],
        responses: { "200": { description: "A page of published insights." } },
      },
    },
    "/discovery/demand-signals": {
      get: {
        tags: ["Discovery"],
        summary: "Demand leaderboard for the most recent completed run",
        description:
          "Resolves MAX(asOf) first and pins to it, so a query running mid-job never " +
          "interleaves two runs and shows two rank-3s. The run's `asOf` is echoed at the " +
          'top level so clients render "as of" and never imply live numbers.',
        parameters: [
          { name: "region", in: "query", schema: { type: "string" } },
          { name: "category", in: "query", schema: { type: "string" } },
          { name: "page", in: "query", schema: { type: "integer" } },
          { name: "limit", in: "query", schema: { type: "integer" } },
        ],
        responses: { "200": { description: "A page of leaderboard rows, plus `asOf`." } },
      },
    },
    "/discovery/talent": {
      get: {
        tags: ["Discovery"],
        summary: "The talent directory",
        description:
          "The ONLY §6 read behind requireAuth, because it is the only one returning other " +
          "people's personal data. `?skill=` is repeatable and multiple values are ANDed. " +
          "`verifiedEffortMinutes` is NULL until §9's ledger exists — never 0.",
        parameters: [
          {
            name: "commitment",
            in: "query",
            schema: { type: "string", enum: ["full_time", "part_time", "hobby"] },
          },
          {
            name: "skill",
            in: "query",
            schema: { type: "array", items: { type: "string" } },
            explode: true,
          },
          {
            name: "availability",
            in: "query",
            schema: { type: "string", enum: ["open_to_work", "open_to_offers", "unavailable"] },
          },
          { name: "region", in: "query", schema: { type: "string" } },
          { name: "sort", in: "query", schema: { type: "string", enum: ["recent", "effort"] } },
          { name: "page", in: "query", schema: { type: "integer" } },
          { name: "limit", in: "query", schema: { type: "integer" } },
        ],
        responses: {
          "200": { description: "A page of published profiles." },
          "401": { $ref: "#/components/responses/Unauthorized" },
        },
      },
    },
    "/discovery/talent/me": {
      get: {
        tags: ["Discovery"],
        summary: "The caller's own profile",
        description:
          "Returns 200 with `data: null` when the caller has not opted in — NOT 404. This " +
          "is an opt-in surface where having no profile is a normal successful state.",
        responses: {
          "200": { description: "The profile, or null." },
          "401": { $ref: "#/components/responses/Unauthorized" },
        },
      },
      put: {
        tags: ["Discovery"],
        summary: "Create or replace the caller's profile (wholesale)",
        description:
          "PUT, not PATCH: the profile is a value object, and wholesale replacement is the " +
          'only way "remove my equity ask" is expressible. A first create ALWAYS lands ' +
          "private — visibility is never a side effect of an edit. " +
          "`currency`, `isPublished`, `verifiedEffortMinutes`, `userId` and skill " +
          "`isVerified` are absent by construction.",
        requestBody: {
          required: true,
          content: {
            "application/json": { schema: { type: "object", additionalProperties: false } },
          },
        },
        responses: {
          "200": { description: "Saved." },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "422": { description: "Unknown skill slug, bad region, or an inverted range." },
        },
      },
      delete: {
        tags: ["Discovery"],
        summary: "Leave the directory",
        responses: {
          "200": { description: "Removed." },
          "404": { description: "No profile to remove." },
        },
      },
    },
    "/discovery/talent/me/publish": {
      post: {
        tags: ["Discovery"],
        summary: "Publish the profile to the directory",
        description: "The completeness gate is re-derived server-side at request time (§0).",
        responses: {
          "200": { description: "Published." },
          "409": { description: "Already published." },
          "422": { description: "Incomplete — the response names what is missing." },
        },
      },
    },
    "/discovery/talent/me/unpublish": {
      post: {
        tags: ["Discovery"],
        summary: "Remove the profile from the directory",
        responses: {
          "200": { description: "Unpublished." },
          "409": { description: "Not published." },
        },
      },
    },
    "/discovery/admin/merge-proposals": {
      get: {
        tags: ["Discovery"],
        summary: "Moderator queue of suspected duplicate clusters",
        description:
          "Requires the `moderate_clusters` platform capability. The capability is checked " +
          "BEFORE any id is read, so a non-staff caller gets an identical 403 for a valid " +
          "id and a garbage one — the route is not an id oracle.",
        responses: {
          "200": { description: "Pending proposals." },
          "403": { description: "Not platform staff." },
        },
      },
    },
    "/discovery/admin/categories/{categoryId}/decide": {
      post: {
        tags: ["Discovery"],
        summary: "Approve or reject a user-minted category",
        description:
          "Requires `moderate_taxonomy`. `note` is REQUIRED on a reject (a rejection with " +
          "no reason is unactionable) and optional on an approve, which is why the body is " +
          "a discriminated union rather than `{ decision, note? }`. Re-deciding is refused " +
          "with 409 rather than treated as idempotent — a second approval would overwrite " +
          "which moderator is accountable.",
        parameters: [
          { name: "categoryId", in: "path", required: true, schema: { type: "string" } },
        ],
        responses: {
          "200": { description: "Decision recorded." },
          "403": { description: "Not platform staff." },
          "404": { description: "No such category." },
          "409": { description: "Already decided." },
        },
      },
    },
    "/discovery/admin/merge-proposals/{proposalId}/decide": {
      post: {
        tags: ["Discovery"],
        summary: "Approve or reject a cluster merge (approval is IRREVERSIBLE)",
        description:
          "Requires `moderate_clusters`. On approval the source cluster's submissions are " +
          "repointed and the source is marked merged; the target's distinctReporterCount is " +
          "RE-DERIVED with COUNT(DISTINCT), never added, because the two clusters almost " +
          "certainly share reporters. The target's opportunity score is invalidated to NULL " +
          "rather than blended — a merged cluster is a new question for the scoring job.",
        parameters: [
          { name: "proposalId", in: "path", required: true, schema: { type: "string" } },
        ],
        responses: {
          "200": { description: "Decision recorded." },
          "403": { description: "Not platform staff." },
          "404": { description: "No such proposal." },
          "409": { description: "Already decided." },
          "422": { description: "Self-merge, or the target was itself already merged." },
        },
      },
    },
    "/api/auth/{splat}": {
      get: {
        tags: ["Better Auth"],
        summary:
          "Better Auth catch-all (GET) — get-session, OAuth redirects, passkey ceremonies, sign-out",
        description:
          "Generated by the `better-auth` library, not this repo. See " +
          "readme-files/BACKEND_STRUCTURE.md §5d for the endpoint table " +
          "(send-verification-otp, sign-in/email, sign-in/social, passkey/*, unlink-account, get-session, ...).",
        parameters: [{ name: "splat", in: "path", required: true, schema: { type: "string" } }],
        responses: { "200": { description: "Varies by sub-route — see Better Auth's own docs." } },
      },
      post: {
        tags: ["Better Auth"],
        summary:
          "Better Auth catch-all (POST) — sign-in, sign-up-blocked OTP, password reset, unlink",
        description:
          "Generated by the `better-auth` library, not this repo. See " +
          "readme-files/BACKEND_STRUCTURE.md §5d for the endpoint table.",
        parameters: [{ name: "splat", in: "path", required: true, schema: { type: "string" } }],
        responses: { "200": { description: "Varies by sub-route — see Better Auth's own docs." } },
      },
    },
  },
};

/**
 * The document served at `/openapi.json`.
 *
 * The R&D paths are merged AFTER the hand-written ones, so a hand-written entry for the
 * same path wins — the detailed description of `/discovery/market-insights` stays, and the
 * derived inventory fills every gap around it.
 */
export const openApiSpec = {
  ...handWrittenSpec,
  tags: [
    ...handWrittenSpec.tags,
    {
      name: "Research and development",
      description:
        "The §11 surface, derived from src/routes/ rather than hand-written. Paths, verbs " +
        "and parameters are exact; bodies and responses are the Zod schemas the " +
        "controllers export (docs/R_AND_D_BACKEND_STRUCTURE.md §11).",
    },
  ],
  paths: { ...buildRndPathItems(), ...handWrittenSpec.paths },
};
