CREATE TABLE "content_category" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"label" text NOT NULL,
	"image_url" text,
	"is_tile" boolean DEFAULT false NOT NULL,
	"sort_order" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "content_category_slug_ck" CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
	CONSTRAINT "content_category_tile_image_ck" CHECK (is_tile = false OR image_url IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "video_category" (
	"video_id" text NOT NULL,
	"category_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "video_category_video_id_category_id_pk" PRIMARY KEY("video_id","category_id")
);
--> statement-breakpoint
ALTER TABLE "video" ADD COLUMN "is_source_verified" boolean DEFAULT false NOT NULL;--> statement-breakpoint
-- HAND-WRITTEN BACKFILL. Not generated by drizzle-kit; do not drop it on a regenerate.
--
-- `is_source_verified` defaults to false, but every YouTube row that already exists was
-- verified SYNCHRONOUSLY at create time: createVideo called oEmbed and refused to insert
-- the row at all if the call did not return 200. Leaving those rows false would assert a
-- false negative as fact — it would empty the §4.5 feed candidate pool and make every
-- pre-existing draft permanently unpublishable, because publishVideo now refuses while
-- the flag is false.
--
-- The predicate IS the set that went through parseAndVerifyYoutubeUrl. Hosted rows (there
-- are none) stay false, because nothing ever verified them.
--
-- This runs in the same transaction as the ADD COLUMN above, deliberately: a separate
-- backfill script would leave a window — however short — in which the studio refuses every
-- publish. It also runs BEFORE video_feed_candidate_idx is built below, so the index is
-- populated once rather than built empty and then filled.
--
-- SCALE NOTE: ADD COLUMN ... DEFAULT ... NOT NULL is metadata-only on PG11+, but this
-- UPDATE rewrites every matching row. Trivial at today's row count. If this table were
-- large it would need batching outside a migration.
UPDATE "video"
SET "is_source_verified" = true
WHERE "video_source" = 'youtube' AND "youtube_video_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "video_category" ADD CONSTRAINT "video_category_video_id_video_id_fk" FOREIGN KEY ("video_id") REFERENCES "public"."video"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_category" ADD CONSTRAINT "video_category_category_id_content_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."content_category"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "content_category_slug_unq" ON "content_category" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "content_category_active_order_idx" ON "content_category" USING btree ("is_active","sort_order");--> statement-breakpoint
CREATE INDEX "video_category_categoryId_idx" ON "video_category" USING btree ("category_id","video_id");--> statement-breakpoint
CREATE INDEX "video_feed_candidate_idx" ON "video" USING btree ("published_at" DESC NULLS LAST) WHERE publish_status = 'published'
            AND visibility = 'public'
            AND upload_status = 'ready'
            AND is_source_verified = true
            AND review_status IN ('not_required', 'approved');