-- ---------------------------------------------------------------------------
-- §12 — PITCHES. Two tables, one status enum, four enum values.
--
-- GENERATED BY `pnpm db:generate`. The header is hand-written because the tool records WHAT
-- changed and never WHY.
--
-- ## What a pitch is, and what it deliberately is not
--
-- A founder publishes an idea or MVP as a video to an audience of funders — Kickstarter and YC
-- demo day, not an application inbox. Qatoto LISTS it and nothing more. The money is somewhere
-- else on purpose: `external_funding_url` points at a licensed third party (Kickstarter, Wefunder,
-- Ketto, a Razorpay page) and `external_contact_url` at a surface the founder owns.
--
-- THE COLUMNS THAT ARE ABSENT ARE THE DESIGN. There is no amount and no equity percentage on
-- `pitch`, because a page carrying "raising $X for Y%" is a general solicitation — and
-- `commerce_cofounder_profile` already refused that exact column pair on that exact ground
-- ("UNTIL DECIDED, THE BACKEND STORES NO CAPITAL FIGURE"). Two tables cannot answer one question
-- differently. There is likewise no pledge, no charge, no custody and no recipient: escrow left
-- this domain (§7), `PLATFORM_FEE_BASIS_POINTS` is 0, and an investor entity would drag KYC and
-- accreditation in behind it.
--
-- ## `pitch_external_urls_ck`
--
-- The two URLs are hostile input that Qatoto renders as links FOR OTHER PEOPLE. `src/lib/
-- external-url.ts` parses, normalizes and refuses them before they are stored — https only, no
-- credentials, no protocol-relative authority, 2048 cap. This CHECK is the backstop that holds if
-- a future write path forgets to call it, in the same spirit as `video_youtube_id_format_ck`.
--
-- ## `pitch_funding_outcome`
--
-- A RECORD OF WHAT TWO PEOPLE SAY HAPPENED, NOT A SETTLEMENT — the contract
-- `research_contribution_ledger_entry` and `compensation_payment_record` already carry. It takes
-- two signatures (`recorded_by_user_id`, then `confirmed_by_user_id`), and
-- `pitch_funding_outcome_two_parties_ck` refuses the same person for both, because two signatures
-- from one person is one signature wearing a hat. No status column and no state machine: it is
-- append-only, so a correction is a new row rather than an edit under somebody's signature.
--
-- ## The four enum values
--
-- `pitch_published` / `pitch_rejected` on BOTH `platform_audit_event_kind` and
-- `notification_kind`. Audit because letting a public solicitation go live names an accountable
-- human; notification because a pitch sits `pending` and invisible until a moderator rules, and
-- the submitter has no other way to learn the answer — the same reason
-- `research_program_published` exists.
--
-- ## Applied by hand, and why
--
-- `pnpm db:migrate` could not run this. Five earlier migrations (0042, 0047, 0049, 0052, 0147)
-- have file hashes that no longer match the rows in `drizzle.__drizzle_migrations`, because this
-- repo's own workflow is to hand-write a header like this one AFTER `db:generate` — and often
-- after applying. drizzle-kit therefore reads those five as pending and dies re-running 0042,
-- with the error swallowed by its spinner. Every statement below was verified against the live
-- database inside a transaction that was rolled back, then applied in one transaction, and the
-- ledger row was inserted with the hash of THIS file as it now stands. Nothing else was touched.
-- ---------------------------------------------------------------------------

CREATE TYPE "public"."pitch_status" AS ENUM('draft', 'pending', 'published', 'rejected', 'closed');--> statement-breakpoint
ALTER TYPE "public"."notification_kind" ADD VALUE 'pitch_published' BEFORE 'video_report_decided';--> statement-breakpoint
ALTER TYPE "public"."notification_kind" ADD VALUE 'pitch_rejected' BEFORE 'video_report_decided';--> statement-breakpoint
ALTER TYPE "public"."platform_audit_event_kind" ADD VALUE 'pitch_published' BEFORE 'promotional_slide_created';--> statement-breakpoint
ALTER TYPE "public"."platform_audit_event_kind" ADD VALUE 'pitch_rejected' BEFORE 'promotional_slide_created';--> statement-breakpoint
CREATE TABLE "pitch" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"project_id" text NOT NULL,
	"title" text NOT NULL,
	"summary" text NOT NULL,
	"pitch_video_id" text,
	"external_funding_url" text,
	"external_contact_url" text,
	"status" "pitch_status" DEFAULT 'draft' NOT NULL,
	"rejection_reason" text,
	"published_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pitch_title_ck" CHECK (char_length(title) BETWEEN 3 AND 120),
	CONSTRAINT "pitch_summary_ck" CHECK (char_length(summary) BETWEEN 20 AND 2000),
	CONSTRAINT "pitch_rejection_reason_ck" CHECK ((status <> 'rejected') OR (rejection_reason IS NOT NULL)),
	CONSTRAINT "pitch_published_at_ck" CHECK ((status <> 'published') OR (published_at IS NOT NULL)),
	CONSTRAINT "pitch_external_urls_ck" CHECK ((external_funding_url IS NULL OR (external_funding_url ~ '^https://' AND char_length(external_funding_url) <= 2048))
          AND (external_contact_url IS NULL OR (external_contact_url ~ '^https://' AND char_length(external_contact_url) <= 2048)))
);
--> statement-breakpoint
CREATE TABLE "pitch_funding_outcome" (
	"id" text PRIMARY KEY NOT NULL,
	"pitch_id" text NOT NULL,
	"amount_in_cents" bigint NOT NULL,
	"currency_code" text NOT NULL,
	"funded_on_date" date NOT NULL,
	"funder_user_id" text,
	"funder_name_text" text NOT NULL,
	"note" text,
	"recorded_by_user_id" text NOT NULL,
	"confirmed_by_user_id" text,
	"confirmed_at" timestamp,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pitch_funding_outcome_amount_ck" CHECK (amount_in_cents > 0 AND currency_code ~ '^[A-Z]{3}$'),
	CONSTRAINT "pitch_funding_outcome_confirmed_ck" CHECK ((confirmed_by_user_id IS NULL) = (confirmed_at IS NULL)),
	CONSTRAINT "pitch_funding_outcome_two_parties_ck" CHECK (confirmed_by_user_id IS NULL OR confirmed_by_user_id <> recorded_by_user_id),
	CONSTRAINT "pitch_funding_outcome_funder_name_ck" CHECK (char_length(funder_name_text) BETWEEN 1 AND 200),
	CONSTRAINT "pitch_funding_outcome_note_ck" CHECK (note IS NULL OR char_length(note) BETWEEN 1 AND 1000),
	CONSTRAINT "pitch_funding_outcome_idempotency_ck" CHECK (char_length(idempotency_key) BETWEEN 8 AND 128)
);
--> statement-breakpoint
ALTER TABLE "pitch" ADD CONSTRAINT "pitch_project_id_research_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."research_project"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pitch" ADD CONSTRAINT "pitch_pitch_video_id_video_id_fk" FOREIGN KEY ("pitch_video_id") REFERENCES "public"."video"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pitch_funding_outcome" ADD CONSTRAINT "pitch_funding_outcome_pitch_id_pitch_id_fk" FOREIGN KEY ("pitch_id") REFERENCES "public"."pitch"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pitch_funding_outcome" ADD CONSTRAINT "pitch_funding_outcome_funder_user_id_user_id_fk" FOREIGN KEY ("funder_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pitch_funding_outcome" ADD CONSTRAINT "pitch_funding_outcome_recorded_by_user_id_user_id_fk" FOREIGN KEY ("recorded_by_user_id") REFERENCES "public"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pitch_funding_outcome" ADD CONSTRAINT "pitch_funding_outcome_confirmed_by_user_id_user_id_fk" FOREIGN KEY ("confirmed_by_user_id") REFERENCES "public"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "pitch_slug_unq" ON "pitch" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "pitch_projectId_idx" ON "pitch" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "pitch_status_idx" ON "pitch" USING btree ("status");--> statement-breakpoint
CREATE INDEX "pitch_status_publishedAt_idx" ON "pitch" USING btree ("status","published_at","id");--> statement-breakpoint
CREATE INDEX "pitch_pitchVideoId_idx" ON "pitch" USING btree ("pitch_video_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pitch_funding_outcome_idempotency_unq" ON "pitch_funding_outcome" USING btree ("recorded_by_user_id","idempotency_key");--> statement-breakpoint
CREATE INDEX "pitch_funding_outcome_pitchId_idx" ON "pitch_funding_outcome" USING btree ("pitch_id","created_at","id");--> statement-breakpoint
CREATE INDEX "pitch_funding_outcome_funderUserId_idx" ON "pitch_funding_outcome" USING btree ("funder_user_id");