-- Keyset pagination correctness: every column below is the sort key of a keyset-paginated
-- list whose cursor is minted with Date.toISOString() / getTime() — MILLISECOND precision
-- (src/modules/store/store-cursor.ts, src/lib/instant-cursor.ts). Stored as plain `timestamp`,
-- Postgres now() gives MICROSECONDS, so the cursor predicate compares .538000 against a stored
-- .538694: DESC lists (lt/eq) SKIP those rows permanently, ASC lists (gt/eq) repeat the cursor row.
--
-- Measured before this migration: 5 orders silently dropped at one real cursor boundary in
-- commerce_order (362 should follow the cursor, 357 returned); 189/189 notification rows,
-- 36/36 commerce_message rows and 102/174 user rows carried sub-millisecond timestamps.
--
-- precision: 3 was already the convention in home.ts (17x), rnd.ts (11x) and most of store.ts
-- (44x) — see the LOAD-BEARING note on video_comment.created_at. This finishes it for the
-- tables that were missed. NOTE: ALTER ... TYPE timestamp(3) ROUNDS rather than truncates;
-- collisions on the same millisecond are absorbed by the id tiebreak every one of these
-- keysets already carries.
--
-- GENERATED BY `pnpm db:generate`. This header is hand-written because the tool records WHAT
-- changed and never WHY.

ALTER TABLE "user" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "user_report" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "user_report" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "notification" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "notification" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_dispute" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_dispute" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_encrypted_document" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_encrypted_document" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_message" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_message" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_order" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_order" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_quote" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_quote" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_refund" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_refund" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_review" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_review" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_rfq" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_rfq" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_service_engagement" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_service_engagement" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_shipment" ALTER COLUMN "created_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_shipment" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "commerce_thread" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (3);--> statement-breakpoint
ALTER TABLE "commerce_thread" ALTER COLUMN "updated_at" SET DEFAULT now();