-- Relation dismissal (§15.8): a moderator can now refuse a compatibility claim, not only confirm it.
--
-- Nullable `dismissed_at` + `dismissed_by_user_id` rather than a new `source_kind` enum member.
-- `source_kind` records PROVENANCE (who asserted the edge); writing a verdict into it would destroy
-- that fact and could not carry attribution anyway, because
-- `commerce_product_relation_verified_ck` forces the attribution columns NULL for every kind that
-- is not `moderator_curated`.
--
-- The moderation index is PARTIAL (`WHERE dismissed_at IS NULL`) because the queue only ever reads
-- rows still awaiting a decision — same idiom as `commerce_product_relation_org_idx`.
--
-- NOTE ON THE ENUM VALUE IN THIS FILE. Postgres forbids USING a value added by
-- `ALTER TYPE ... ADD VALUE` in the transaction that added it, and drizzle runs each migration in
-- one transaction — which is why `0152` and `0156` are enum-only files. That restriction does NOT
-- apply here: no statement below references the `'product_relation_dismissed'` LABEL. The two
-- identifiers that merely contain the substring are the constraint and FK names
-- (`commerce_product_relation_dismissed_ck`, `..._dismissed_by_user_id_user_id_fk`). Verified
-- against server_version 17.11.
--
-- GENERATED BY `pnpm db:generate`. This header is hand-written because the tool records WHAT
-- changed and never WHY.

ALTER TYPE "public"."commerce_organization_audit_event_kind" ADD VALUE 'product_relation_dismissed' BEFORE 'pathway_created';--> statement-breakpoint
ALTER TABLE "commerce_product_relation" ADD COLUMN "dismissed_by_user_id" text;--> statement-breakpoint
ALTER TABLE "commerce_product_relation" ADD COLUMN "dismissed_at" timestamp;--> statement-breakpoint
ALTER TABLE "commerce_product_relation" ADD CONSTRAINT "commerce_product_relation_dismissed_by_user_id_user_id_fk" FOREIGN KEY ("dismissed_by_user_id") REFERENCES "public"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "commerce_product_relation_moderation_idx" ON "commerce_product_relation" USING btree ("source_kind","created_at","id") WHERE dismissed_at IS NULL;--> statement-breakpoint
ALTER TABLE "commerce_product_relation" ADD CONSTRAINT "commerce_product_relation_dismissed_ck" CHECK ((dismissed_at IS NULL AND dismissed_by_user_id IS NULL)
          OR (dismissed_at IS NOT NULL AND dismissed_by_user_id IS NOT NULL));