-- Third-party declarations on orders, and the RFQ -> goods-order link.
--
-- commerce_order_third_party_declaration: a party's self-reported cargo cover, storage cover or
-- laboratory test report for an order. A claim, never an observation; the server stamps the
-- disclaimer version the author acknowledged.
--
-- related_order_id on commerce_rfq and commerce_order: accepting a quote always opens a new order,
-- so a service bought for a shipment needs a link back to that shipment's order.
--
-- Generated by db:generate; no hand edits beyond this header.
CREATE TYPE "public"."commerce_order_party_side" AS ENUM('buyer', 'counterparty');--> statement-breakpoint
CREATE TYPE "public"."commerce_third_party_declaration_kind" AS ENUM('transit_cover', 'storage_cover', 'test_report');--> statement-breakpoint
CREATE TABLE "commerce_order_third_party_declaration" (
	"id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"shipment_leg_id" text,
	"kind" "commerce_third_party_declaration_kind" NOT NULL,
	"declared_by_side" "commerce_order_party_side" NOT NULL,
	"declared_by_organization_id" text NOT NULL,
	"declared_by_member_id" text NOT NULL,
	"issuer" text NOT NULL,
	"reference" text NOT NULL,
	"coverage_class" text,
	"standard" text,
	"coverage_amount_in_cents" bigint,
	"coverage_currency" text,
	"valid_from" date,
	"valid_until" date,
	"issued_on" date,
	"evidence_document_id" text,
	"note" text,
	"disclaimer_version" text NOT NULL,
	"withdrawn_at" timestamp,
	"withdrawn_by_member_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "commerce_order_third_party_declaration_text_ck" CHECK (char_length(issuer) BETWEEN 1 AND 200 AND char_length(reference) BETWEEN 1 AND 100 AND (coverage_class IS NULL OR char_length(coverage_class) BETWEEN 1 AND 80) AND (standard IS NULL OR char_length(standard) BETWEEN 1 AND 200) AND (note IS NULL OR char_length(note) BETWEEN 1 AND 1000) AND char_length(disclaimer_version) BETWEEN 1 AND 64),
	CONSTRAINT "commerce_order_third_party_declaration_coverage_ck" CHECK ((coverage_amount_in_cents IS NULL AND coverage_currency IS NULL) OR (coverage_amount_in_cents > 0 AND coverage_currency ~ '^[A-Z]{3}$')),
	CONSTRAINT "commerce_order_third_party_declaration_validity_ck" CHECK (valid_from IS NULL OR valid_until IS NULL OR valid_until >= valid_from),
	CONSTRAINT "commerce_order_third_party_declaration_kind_shape_ck" CHECK ((kind = 'test_report' AND standard IS NOT NULL AND coverage_class IS NULL AND coverage_amount_in_cents IS NULL AND shipment_leg_id IS NULL) OR (kind = 'transit_cover' AND standard IS NULL AND issued_on IS NULL) OR (kind = 'storage_cover' AND standard IS NULL AND issued_on IS NULL AND shipment_leg_id IS NULL)),
	CONSTRAINT "commerce_order_third_party_declaration_withdrawn_ck" CHECK ((withdrawn_at IS NULL) = (withdrawn_by_member_id IS NULL))
);
--> statement-breakpoint
ALTER TABLE "commerce_order" ADD COLUMN "related_order_id" text;--> statement-breakpoint
ALTER TABLE "commerce_rfq" ADD COLUMN "related_order_id" text;--> statement-breakpoint
ALTER TABLE "commerce_order_third_party_declaration" ADD CONSTRAINT "commerce_order_third_party_declaration_order_id_commerce_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."commerce_order"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commerce_order_third_party_declaration" ADD CONSTRAINT "commerce_order_third_party_declaration_shipment_leg_id_commerce_shipment_leg_id_fk" FOREIGN KEY ("shipment_leg_id") REFERENCES "public"."commerce_shipment_leg"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commerce_order_third_party_declaration" ADD CONSTRAINT "commerce_order_third_party_declaration_declared_by_organization_id_commerce_organization_id_fk" FOREIGN KEY ("declared_by_organization_id") REFERENCES "public"."commerce_organization"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commerce_order_third_party_declaration" ADD CONSTRAINT "commerce_order_third_party_declaration_declared_by_member_id_commerce_organization_member_id_fk" FOREIGN KEY ("declared_by_member_id") REFERENCES "public"."commerce_organization_member"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commerce_order_third_party_declaration" ADD CONSTRAINT "commerce_order_third_party_declaration_evidence_document_id_commerce_encrypted_document_id_fk" FOREIGN KEY ("evidence_document_id") REFERENCES "public"."commerce_encrypted_document"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commerce_order_third_party_declaration" ADD CONSTRAINT "commerce_order_third_party_declaration_withdrawn_by_member_id_commerce_organization_member_id_fk" FOREIGN KEY ("withdrawn_by_member_id") REFERENCES "public"."commerce_organization_member"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "commerce_order_third_party_declaration_order_idx" ON "commerce_order_third_party_declaration" USING btree ("order_id","created_at");--> statement-breakpoint
ALTER TABLE "commerce_order" ADD CONSTRAINT "commerce_order_related_order_id_commerce_order_id_fk" FOREIGN KEY ("related_order_id") REFERENCES "public"."commerce_order"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commerce_rfq" ADD CONSTRAINT "commerce_rfq_related_order_id_commerce_order_id_fk" FOREIGN KEY ("related_order_id") REFERENCES "public"."commerce_order"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "commerce_order_related_order_idx" ON "commerce_order" USING btree ("related_order_id");