-- Multi-axis product variants (STORE_BACKEND_STRUCTURE.md A26).
--
-- commerce_product_variant_option: one value of one option axis ("Colour: Sea blue") on a variant,
-- at most three axes per variant. Axes are a browse construct; the variant stays the buyable,
-- snapshotted unit, so nothing transactional references this table.
--
-- Generated by db:generate; the ownership-guard trigger at the end is appended by hand, reusing
-- commerce_variant_ownership_guard_fn from 0054 exactly as 0055 does for the prepare line.

CREATE TABLE "commerce_product_variant_option" (
	"id" text PRIMARY KEY NOT NULL,
	"product_id" text NOT NULL,
	"variant_id" text NOT NULL,
	"option_name" text NOT NULL,
	"option_value" text NOT NULL,
	"position" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "commerce_product_variant_option_name_ck" CHECK (char_length(option_name) BETWEEN 1 AND 40),
	CONSTRAINT "commerce_product_variant_option_value_ck" CHECK (char_length(option_value) BETWEEN 1 AND 36),
	CONSTRAINT "commerce_product_variant_option_position_ck" CHECK (position BETWEEN 0 AND 2)
);
--> statement-breakpoint
ALTER TABLE "commerce_product_variant_option" ADD CONSTRAINT "commerce_product_variant_option_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commerce_product_variant_option" ADD CONSTRAINT "commerce_product_variant_option_variant_id_commerce_product_variant_id_fk" FOREIGN KEY ("variant_id") REFERENCES "public"."commerce_product_variant"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "commerce_product_variant_option_name_uidx" ON "commerce_product_variant_option" USING btree ("variant_id","option_name");--> statement-breakpoint
CREATE UNIQUE INDEX "commerce_product_variant_option_position_uidx" ON "commerce_product_variant_option" USING btree ("variant_id","position");--> statement-breakpoint
CREATE INDEX "commerce_product_variant_option_product_idx" ON "commerce_product_variant_option" USING btree ("product_id");--> statement-breakpoint
CREATE TRIGGER "commerce_product_variant_option_variant_guard"
  BEFORE INSERT OR UPDATE ON "commerce_product_variant_option"
  FOR EACH ROW EXECUTE FUNCTION "commerce_variant_ownership_guard_fn"();
