-- commerce_order.settlement_rail loses its 'internal_custody' default (store.ts carries the reasoning).
--
-- The default was right for the rows 0087 added the column to, and wrong for every insert since:
-- one that forgot the rail became a frozen custody order nothing can pay. Existing rows keep
-- their rail; the snapshot trigger makes them immutable anyway. Generated by db:generate; no hand
-- edits beyond this header.

ALTER TABLE "commerce_order" ALTER COLUMN "settlement_rail" DROP DEFAULT;